### ISSUE TITLE
TestSuite work_dir ut fails

### ISSUE THREAD

**Issue by UnDarkle** [gregoil/rotest#6]
======================================================================
FAIL: test_working_dir (rotest.tests.core.test_suite.TestTestSuite)
Test the tests working directories creation and structure.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\gits\rotest\rotest\tests\core\test_suite.py", line 335, in test_working_dir
    (test_suite.data, test_suite.work_dir, ROTEST_WORK_DIR))
AssertionError: Test MockTestSuite_None work directory 'C:/gits/work_dir/MockTestSuite_17.08.21_15_10_16(0)' is not contained in the base work directory 'C:/gits/work_dir/'

**Comment by osherdp** [comment]
Doesn't happen anymore
